version: "2"

volumes:
  data_redis:
    driver: local


services:


  code:
    image: alpine
    stdin_open: true
    entrypoint:
      - ash
    volumes:
      - ../:/app



#  Container for service
  workspace:
    build:
      context: ./php
      args:
        - INSTALL_XDEBUG=true
        - INSTALL_PHPUNIT=true
        - INSTALL_COMPOSER=true
    volumes_from:
      - code
    links:
      - web
      - redis
    env_file:
      - base.env
    tty: true
    working_dir: /app
    command: sh -c "php artisan queue:restart && sh"



#  PHP-FPM
  php:
    build:
      context: ./php
      args:
        - INSTALL_XDEBUG=true
        - INSTALL_PHPUNIT=true
    volumes_from:
      - code
    links:
      - redis
    env_file:
      - base.env




#  Sms Jobs dispatcher
  worker-email-sender:
    build:
      context: ./php
    volumes_from:
      - code
    links:
      - redis
    env_file:
      - base.env
    working_dir: /app
    restart: always
    command: php artisan queue:work --tries=3




# nginx
  web:
    build:
      context: ./nginx
    volumes_from:
      - code
    ports:
      - 80:80
    links:
      - php
    environment:
     - NGINX_HOST=sms.in
     - NGINX_PORT=80
     - FPM_HOST=php
     - FPM_PORT=9000
    #command: /bin/bash -c "envsubst '$$NGINX_HOST $$NGINX_PORT $$FPM_HOST $$FPM_PORT' < /etc/nginx/conf.d/sms_service.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"




  redis:
    image: redis
    volumes:
      - data_redis:/data




  mailhog:
    image: mailhog/mailhog
    ports:
      - 8080:8025












